baseURL = "https://tech-snippets.web.app/"
languageCode = "en-us"
title = "Mordy's Tech Snippets"
theme = "mixedpaper"
pygmentsUseClasses = true
googleAnalytics = "UA-185006741-1"

[params.comment]
type = "disqus"

disqusShortname = "tech-snippets"

[ params ]
description = "A small blog where I post random snippets of my computer and coding knowledge"
showReadMore = false
mainSections = [
"posts",
]
listPaginate = 20

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

# [[menu.main]]
# identifier = "posts"
# name = "All Posts"
# url = "/posts/"
# weight = 2

[[menu.main]]
name = "Archives"
identifier = "archives"
url = "/archives/"
weight = 3

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false